export const ROMAJI_REPLACEMENTS: ReadonlyArray<readonly [string, string]> = [
    ["shi", "si"],
    ["chi", "ti"],
    ["tsu", "tu"],
    ["fu", "hu"],
    ["ji", "zi"],
    ["sha", "sya"],
    ["sho", "syo"],
    ["shu", "syu"],
    ["cha", "tya"],
    ["cho", "tyo"],
    ["chu", "tyu"],
] as const;

export const CLASSROOM_PATTERNS: readonly RegExp[] = [
    /^(.+?)\s*さんが\s*(.+?)\s*を使用して新しい課題を投稿しました:\s*(.+)$/,
    /^(.+?)\s*さんが\s*(.+?)\s*を使用して(.+?)を投稿しました:\s*(.+)$/,
    /^(.+?)\s*さんが\s*(.+?)\s*を使用して(.+?)を投稿しました\.?\s*(.*)$/,
    /^(.+?)\s*さんが\s*(.+?)\s*を投稿しました:\s*(.+)$/,
    /^(.+?)\s*さんが\s*(.+?)\s*を投稿しました\.?\s*(.*)$/,
    /^(.+?)\s*さんが\s*(.+?)\s*を投稿しました\.?$/,
    /^(.+?)\s*さんが\s*(.+?)\s*をしました\.?$/,
    /^(.+?)\s*さんが\s*(.+?)しました\.?$/,
];

export const TARGET_SELECTORS: readonly string[] = [
    ".Cx437e",
    ".Vu2fZd",
    ".zo5Hg",
    ".A6dC2c",
    "h2.jzdBjc",
    "a.Vu2fZd",
    'span[class*="VGBb"]',
    'div[class*="VGBb"]',
    'div[class*="QRIHxd"]',
    'div[class*="usn0cc"]',
    'div[class*="iOB96"]',
    'span[class*="post"]',
    'div[class*="post"]',
    'span[class*="message"]',
    'div[class*="message"]',
    'span[class*="content"]',
    'div[class*="content"]',
    'span[class*="text"]',
    'div[class*="text"]',
    'span[class*="body"]',
    'div[class*="body"]',
    'span[class*="description"]',
    'div[class*="description"]',
    'span[class*="Pc9Gce"]',
    'div[class*="Pc9Gce"]',
    'span[class*="DShyMc"]',
    'div[class*="DShyMc"]',
    'span[class*="wJD2Bb"]',
    'div[class*="wJD2Bb"]',
    'span[class*="YMvIgc"]',
    'div[class*="YMvIgc"]',
    'span[class*="CYZpAe"]',
    'div[class*="CYZpAe"]',
    'span[class*="YVvGBb"]',
    'div[class*="YVvGBb"]',
];

export const DROPDOWN_SELECTORS: readonly string[] = [
    'ul[role="listbox"]',
    'div[role="listbox"]',
    'div[role="menu"]',
    ".JPdR6b",
];

export const ITEM_SELECTORS: readonly string[] = [
    'li[role="option"]',
    'div[role="option"]',
    'div[role="menuitem"]',
    "span.jB3rtd",
];
